### PR TITLE
fix: fix invalid input for long squeeth chart

### PR DESCRIPTION
**Pull request by iamoperand**
# Task:

"0" is not a valid input for historical days, but we still process it and get stuck. This PR fixes that.

### Before
Screenshot 2022-12-02 at 5 31 32 PM

### After
Screenshot 2022-12-02 at 5 31 53 PM

## Type of change

- [ ] New feature
- [x] Bug fix
- [ ] Testing code
- [ ] Document update or config files

### CODE REVIEW

**Review by KMKoushik — APPROVED** [review]
LGTM

**Review by alexisgauba — CHANGES_REQUESTED** [review]
zk's feedback was instead of showing an error message, don't let the user input 0 and instead start the input at 1 instead of 0

**Comment by alexisgauba** [comment]
Updating the PR: next step here is to add start and end dates before we can merge per convo with @KMKoushik @iamoperand @zkoticha

**Comment by iamoperand** [comment]
closing this as @rushikeshakhare has another PR for it: https://github.com/opynfinance/squeeth-monorepo/pull/798

**Pull request closed without merging**
