### PR TITLE
fix: add recipient condition check to position & txs for showing crab…

### LINKED ISSUE #166: Don't show a "short" position if a user has a crab deposit
**Describe the bug**
Crab deposits are being counted as Uniswap sells, showing users that they have a short position on the position card when it shouldn't show anything since a crab position is distinct from a short position 

**To Reproduce**
- Open a crab position

**Expected behavior**
- Show crab on the positions tab 
- Show nothing on the trade page position card

**Screenshots**
Screenshot 2022-02-14 at 9 46 30 AM
Screenshot 2022-02-14 at 9 47 50 AM

### PR DESCRIPTION
**Pull request by yichiehliu**
… as short position

# Task:

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #166  (issue)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Document update

## How Has This Been Tested

Locally
## Checklist

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] Added video recordings if it is a UI change

### CODE REVIEW

**Comment by EstherSeyi** [comment]
I still have the issue of swaps not loading. I have a long position here and also I'm missing some transaction history on the positions page.

Screenshot 2022-02-16 at 10 12 02
Screenshot 2022-02-16 at 10 12 09

**Comment by yichiehliu** [comment]
> I still have the issue of swaps not loading. I have a long position here and also I'm missing some transaction history on the positions page.
> 
> Screenshot 2022-02-16 at 10 12 02
> 
> Screenshot 2022-02-16 at 10 12 09

ok, I think I will separate the fixes into two PRs tho, this will fix the issue #166

**Comment by KMKoushik** [comment]
It also removed my Buy transaction. So now it doesn't show any position

squeeth.com:
Screenshot 2022-02-17 at 8 10 58 AM

Preview:
Screenshot 2022-02-17 at 8 12 19 AM

**Comment by alexisgauba** [comment]
> 

does squeeth.com show your buy txn?

**Comment by KMKoushik** [comment]
Might not be related but the position is reloaded in a time interval and UI is stuttering 

https://user-images.githubusercontent.com/24666922/154771385-17ad52a6-eda1-4647-9cce-c2e6e73747df.mov

**Review by KMKoushik — APPROVED** [review]

**Review by alexisgauba — APPROVED** [review]

**Pull request merged**
