### PR TITLE
Stop user from being restricted on ropsten

### PR DESCRIPTION
**Pull request by EstherSeyi**
# Task:

## Description

This PR Removes ropsten blocking

Fixes # (issue)
#141 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Document update

## How Has This Been Tested

Please describe how to test to verify the changes. Provide instructions so we can reproduce.

## Checklist

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] Added video recordings if it is a UI change

### CODE REVIEW

**Review by yichiehliu — COMMENTED** [review]
image
if I switched to ropsten, I would get this error🤔

**Comment by EstherSeyi** [comment]
> https://continuouscall-git-fe-remove-ropsten-blocking-opynfinance.vercel.app

what's the error on your console?

**Comment by yichiehliu** [comment]
> > https://continuouscall-git-fe-remove-ropsten-blocking-opynfinance.vercel.app
> 
> what's the error on your console? @yichiehliu

image

**Comment by EstherSeyi** [comment]
I am not experiencing this.

**Comment by yichiehliu** [comment]
Lol, it worked for me now, I think the changes make sense to me, but not sure if users will experience the same as I did

**Review by alexisgauba — APPROVED** [review]

**Pull request merged**
