### PR TITLE
feat: dequeue analytics

### PR DESCRIPTION
**Pull request by rushikeshakhare**
# Task:

Following events are added

CANCEL_DEPOSIT_STN_CRAB_USDC_CLICK 
CANCEL_DEPOSIT_STN_CRAB_USDC_SUCCESS 
CANCEL_DEPOSIT_STN_CRAB_USDC_REVERT 
CANCEL_DEPOSIT_STN_CRAB_USDC_FAILED
  
CANCEL_WITHDRAW_STN_CRAB_USDC_CLICK 
CANCEL_WITHDRAW_STN_CRAB_USDC_SUCCESS 
CANCEL_WITHDRAW_STN_CRAB_USDC_REVERT 
CANCEL_WITHDRAW_STN_CRAB_USDC_FAILED 

## Type of change

- [x] New feature
- [ ] Bug fix
- [ ] Testing code
- [ ] Document update or config files

### CODE REVIEW

**Review by KMKoushik — APPROVED** [review]

**Comment by KMKoushik** [comment]
@sanandnarayan Check this once and we can merge it

**Comment by sanandnarayan** [comment]
Please rename Revert to reject?

**Review by sanandnarayan — APPROVED** [review]
Approved, If possible please rename revert to reject

**Comment by rushikeshakhare** [comment]
> Approved, If possible please rename revert to reject

renamed to Reject

**Pull request merged**
