### PR TITLE
feat: show strike count modal everytime user gets a strike

### PR DESCRIPTION
**Pull request by iamoperand**
# Task:
Show strike count popup/banner, everytime user gets a strike

## Description
- There are 2 modals now:
  - StrikeWarningModal: that shows up if the wallet isn't connected. Tells the user when they would be getting a strike.
  - StrikeCountModal: shows up when user gets a strike. Shows the strike count.  
  
Fixes ENG-1835

## Type of change

- [x] New feature
- [ ] Bug fix
- [ ] Testing code
- [ ] Document update or config files

### CODE REVIEW

**Review by alpinechicken — CHANGES_REQUESTED** [review]
mostly lgtm.

Few things:

- Change text to explain strike. 

‘[Opyn.co](http://opyn.co/) is not available to US users. You have attempted to join from a US IP address. You currently have {addressStrikeCount} strike(s)” ….

- After I have three strikes the visitorCount increments no matter where I join from.  Maybe just give the blocked message for visitorCount>3

“Your wallet address is blocked for violating our terms of service. You cannot open any new positions. You can still close positions and remove collateral from vaults.“


- Blocked address should be able to close long/short positions on /squeeth. Currently can close short but not close long.

**Comment by aleone** [comment]
> mostly lgtm.
> 
> Few things:
> 
> * Change text to explain strike.
> 
> ‘You have attempted to access opyn.co from a restricted territory. You currently have {addressStrikeCount} strike(s)” ….
> 
> * After I have three strikes the visitorCount increments no matter where I join from.  Maybe just give the blocked message for visitorCount>3
> 
> “Your wallet address is blocked for violating our terms of service. You cannot open any new positions. You can still close positions and remove collateral from vaults.“
> 
> * Blocked address should be able to close long/short positions on /squeeth. Currently can close short but not close long.

Is burning oSQTH not possible as well?

**Review by alpinechicken — APPROVED** [review]
lgtm - changed warning boxes for clarity

**Review by sanandnarayan — APPROVED** [review]
looks good to me

**Pull request merged**
