### PR TITLE
update comments for generalSwap and update e2e to use fixed block for mainnet fork

### PR DESCRIPTION
**Pull request by aleone**
# Task: Update comments to make limitations of generalSwap clear and update e2e testing to use fixed block number

## Description
- add fixed block number for mainnet fork in e2e testing
- Update comments around the general swap action to make it clear it will cause loss of funds if used with any token other than weth and wPowerPerp

Fixes # (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Document update

## How Has This Been Tested

Please describe how to test to verify the changes. Provide instructions so we can reproduce.

## FE Checklist

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] Added video recordings if it is a UI change

## User Facing Checklist

- [ ] I fully understand the user problem this PR is solving
- [ ] I know who the target user is for this PR and have a deep understanding of that user
- [ ] I have tried this flow thinking from the pov of the target user for this PR
- [ ] I (or working w someone on team) have scheduled a user test for this PR (if it is a large change)

### CODE REVIEW

**Review by alpinechicken — APPROVED** [review]
lgtm

**Review by daryakaviani — APPROVED** [review]
looks good!

**Review by alpinechicken — APPROVED** [review]
lg

**Review by alpinechicken — APPROVED** [review]
this may save our lives

**Pull request merged**
