### PR TITLE
[Audit Fix] - [L-8] - Add zero address checks to CrabMigration.sol constructor

### PR DESCRIPTION
**Pull request by daryakaviani**
Added zero address check for contract constructor for constructor parameter addresses.

### CODE REVIEW

**Review by aleone — CHANGES_REQUESTED** [review]
Can you add unit tests for the expected reverts - similar to what we do for crab-strategy-v2 in the unit tests?

**Comment by daryakaviani** [comment]
> Can you add unit tests for the expected reverts - similar to what we do for crab-strategy-v2 in the unit tests?

Added!

**Review by aparnakr — APPROVED** [review]

**Review by aleone — CHANGES_REQUESTED** [review]
Can you have a test for weth = address(0) and crabv1 = address(0) so we know that all inputs will revert w address(0).

**Review by alpinechicken — APPROVED** [review]
lgtm

**Comment by daryakaviani** [comment]
> Can you have a test for weth = address(0) and crabv1 = address(0) so we know that all inputs will revert w address(0).

Updated. CrabV1 reverted, but weth did not. Should we also add this check in `CrabStrategyV2.sol` then since we have an unchecked weth address being set?

**Review by aleone — APPROVED** [review]
lgtm

**Comment by daryakaviani** [comment]
note: don't merge until 574 is merged + subsequent edit is made

**Pull request merged**
