### PR TITLE
Configure atom test and add pnl tests

### PR DESCRIPTION
**Pull request by adam5909099**
## Description
Configure atom test infrastructure and add tests for pnl as an example

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Document update

## How Has This Been Tested

Please describe how to test to verify the changes. Provide instructions so we can reproduce.

## Checklist

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] Added video recordings if it is a UI change

### CODE REVIEW

**Comment by KMKoushik** [comment]
@adam5909099 If it's not ready to review mark it as draft PR

**Review by yichiehliu — COMMENTED** [review]
@adam5909099 The vercel seemed not being deployed successfully

**Comment by KMKoushik** [comment]
@adam5909099 Will merge this after the learning session

**Comment by KMKoushik** [comment]
BTW, Can we add it CI?

**Comment by adam5909099** [comment]
@KMKoushik I added a new step for running Frontend tests. This PR is ready to be merged.

**Review by KMKoushik — APPROVED** [review]

**Pull request merged**
