### PR TITLE
Replace transfers with safeTransfer in hedgeOTC function

### PR DESCRIPTION
**Pull request by sanandnarayan**
Replace transfers with safeTransfer in hedgeOTC function

### CODE REVIEW

**Review by alpinechicken — COMMENTED** [review]
also in strategyFlash 459 and 480?

**Review by aparnakr — APPROVED** [review]

**Review by aleone — APPROVED** [review]
I am ok with merging, but after looking into it more, think that we are actually increasing gas costs for users with no improvement in security as we know that squeeth and weth are conforming erc-20s. But again, ok w it.

**Comment by aleone** [comment]
I am ok with merging, but after looking into it more, think that we are actually increasing gas costs for users with no improvement in security as we know that squeeth and weth are conforming erc-20s. But again, ok w it.

**Comment by sanandnarayan** [comment]
@aleone agree, closing this PR without merging

**Pull request closed without merging**
