### PR TITLE
add pokt support

### PR DESCRIPTION
**Pull request by akwritescode**
# Task:

add pokt support

## Description

Adding pokt network as RPC service provider
note: merging this wont make pokt default rpc provider. we should also change the flags in .env after

Fixes # (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Document update

## How Has This Been Tested

Tested the normal operations ( buy, sell, mint + sell etc ) on my local
Saw in network tab that calls are going to pokt instead of alchemy.
also seen in the pokt account dashboard that the calls are being served without errors

## Checklist

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] Added video recordings if it is a UI change

### CODE REVIEW

**Review by KMKoushik — APPROVED** [review]

**Review by alexisgauba — APPROVED** [review]

**Comment by alexisgauba** [comment]
good to go once rebased imo

**Comment by KMKoushik** [comment]
All good @akwritescode! Need to add vercel configs, right?

**Comment by akwritescode** [comment]
hey @KMKoushik so pushed a rebase.
so merging this as is, should not change anything on PROD

when we want to enable pokt via config changes, we should co-ordinate to make sure someone has an eye on the usage to make sure bad things are not happening and we arent getting errors. we can take shifts based on when u and me are awake

**Comment by KMKoushik** [comment]
Sounds good!

**Pull request merged**
