### PR TITLE
Add Foundry

### PR DESCRIPTION
**Pull request by haythem96**
# Add Foundry

## Description

Screen Shot 2022-05-02 at 10 36 44 AM

- Added foundry
- Moved hardhat tests inside `/test/hardhat-test`
- Create `/test/foundry-test/` for solidity tests

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Document update

## How Has This Been Tested

Please describe how to test to verify the changes. Provide instructions so we can reproduce.

## Checklist

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] Added video recordings if it is a UI change

### CODE REVIEW

**Comment by haythem96** [comment]
`Forge test` will fail for now because we have functions that start with `test...` but they are not meant to be testing functions. Opened an issue in Foundry https://github.com/foundry-rs/foundry/issues/1499

**Comment by haythem96** [comment]
Need to configure a different path for hardhat cache to not conflict with foundry's

**Review by alpinechicken — APPROVED** [review]
lgtm. what a time to be alive!

**Comment by haythem96** [comment]
Closing this for now

**Pull request closed without merging**
