### PR TITLE
Add collateral you redeem

### PR DESCRIPTION
**Pull request by adam5909099**
# Task:
This PR involves refactoring the existing logic of ShortClose so needs a detailed review.

## Description
Add collateral Eth input and refactored dependency logic 
image

Fixes https://github.com/opynfinance/squeeth-monorepo/issues/370

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Document update

## How Has This Been Tested

Please describe how to test to verify the changes. Provide instructions so we can reproduce.

## Checklist

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] Added video recordings if it is a UI change

### CODE REVIEW

**Comment by KMKoushik** [comment]
@adam5909099 Can you explain what has been done clearly? PRs like this might have to go through @alexisgauba and user story should be documented!

**Comment by adam5909099** [comment]
@alexisgauba, Can you please review this PR for allowing users to enter collateral? I kept the Spend card for now because I'm not sure how to label the two values contained in the Card.

**Comment by alexisgauba** [comment]
Yep, Adam and I chatted about this earlier! Main thing is giving users the ability to input the amount of ETH they want to remove from a vault when they are partially closing, some advanced users would just use amount to buy back + burn & collRatio to guess and check amount of ETH to remove, when what they wanted to input was a certain amount of ETH to get out and then see how that affects their position 

Adding the field for Collateral to redeem the way you did LGTM visually 

One good thing to add would be the liquidation price of the vault after the change. The key things advanced users were looking at were 
- How much ETH can I remove from the vault 
- What liquidation price will that leave me at  

Imo could just add "New liquidation price" as a row right above "Current collateral ratio" 

From a logic pov, seems like the value is a bit different than on the current deployment? Seems like something might be going on there? 
Screen Shot 2022-05-06 at 2 59 00 PM
Screen Shot 2022-05-06 at 2 59 12 PM

**Comment by KMKoushik** [comment]
@adam5909099 Can you take a look at this?

**Comment by adam5909099** [comment]
@alexisgauba For different collateral value between this PR and production isn't an issue. It's related to the time when the website is loaded.

1.
image
2.
image

The above screenshots are from production when closing two oSQTH in short. They show different values because they were loaded at other times. So I don't think it's an issue.

CC @KMKoushik

**Comment by alexisgauba** [comment]
Ok gotcha, then in that case I think the main think would just be adding "New liquidation price" as a row right above "Current collateral ratio"

**Comment by adam5909099** [comment]
@alexisgauba, I got it, thank you. I added a new liquidation price, but I don't think it's calculated correctly. Can you or @KMKoushik provide me the formula for calculating it in a short close or a notion doc that I can reference?

**Comment by adam5909099** [comment]
@KMKoushik I updated PR as you mentioned. When I set 0.2869 collateral eth, the new liquidation price was 4866.64, like in the following screenshot.
image
After partially closing short (it took about 15 seconds) and going to the manage vault page, the liquidation price was shown as 4866.63
image
There's a 0.01 difference, but I think it's related to underlying value changes while closing short and not an issue.

**Review by KMKoushik — APPROVED** [review]

**Review by KMKoushik — CHANGES_REQUESTED** [review]
Can we stop having -ve value here? We can stop slider when it reaches 0
Screen Shot 2022-05-13 at 1 44 57 pm

**Comment by adam5909099** [comment]
@KMKoushik I add a restriction to the slider to ensure eth is bigger than 0. Can you please review it again?

**Pull request closed without merging**
