### PR TITLE
[WIP] Bull Auction: Leverage Rebalance

### PR DESCRIPTION
**Pull request by daryakaviani**
Bull auction skeleton & leverage rebalance

### CODE REVIEW

**Comment by haythem96** [comment]
Did some refactoring, added owners and manager addresses, moved some state variables to the auction contract, should looks fine I guess.

**Comment by haythem96** [comment]
Let's try to not work both on the same PR so we will not have biased review, so I think you can take it from there.

**Comment by haythem96** [comment]
Also will be better to merge this with `fix/crab-balance-internal-state` branch and make this PR merge there also @daryakaviani

**Comment by daryakaviani** [comment]
Updated to https://github.com/opynfinance/squeeth-monorepo/pull/699

**Pull request closed without merging**
